## Config file for afterburner.py

name_of_known_language : English
name_of_target_language : Italian
name_of_phrases_csv : /Users/aleks/repos/afterburner/assets/afterburner_inputs_english_to_italian_part_1.csv
path_to_sqlite_file : ./afterburner_english_to_italian.sqlite