## Config file for afterburner.py

name_of_known_language : English
name_of_target_language : Italian
name_of_phrases_csv : phrases_english_to_italian.csv
path_to_sqlite_file : ./afterburner_english_to_italian.sqlite